Chapter_6/Lessons21/boat/urls.py
from django.urls import path

from boat.apps import BoatConfig

from boat.views import BoatListView, BoatDetailView

app_name = BoatConfig.name

urlpatterns = [
    path('', BoatListView.as_view(), name='boat_list'),
    path('<int:pk>/', BoatDetailView.as_view(), name='boat_view')
]

Chapter_6/Lessons21/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('boat.urls', namespace='boat')),
    path('order/', include('order.urls', namespace='order')),
]

Chapter_6/Lessons21/order/urls.py
from django.urls import path

from order.views import OrderCreateView

from order.apps import OrderConfig

app_name = OrderConfig.name
urlpatterns = [
    path('create/<int:pk>/', OrderCreateView.as_view(), name='create')
]

Chapter_6/Lessons21/boat/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Owner(models.Model):
    name = models.CharField(max_length=20, verbose_name="имя")
    email = models.EmailField(verbose_name="email", unique=True)

    def __str__(self):
        return f'{self.name} - {self.email}'

    class Meta:
        verbose_name = "владелец"
        verbose_name_plural = "владельцы"


class Boat(models.Model):
    name = models.CharField(max_length=50, verbose_name="название")
    year = models.PositiveSmallIntegerField(**NULLABLE, verbose_name="год выпуска")
    owner = models.ForeignKey(Owner, verbose_name="владелец", on_delete=models.CASCADE)
    price = models.IntegerField(**NULLABLE, verbose_name="цена")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "лодка"
        verbose_name_plural = "лодки"


class BoatHistory(models.Model):
    boat = models.ForeignKey(Boat, on_delete=models.CASCADE, verbose_name="лодка")
    start_year = models.PositiveSmallIntegerField(**NULLABLE, verbose_name="владел c")
    stop_year = models.PositiveSmallIntegerField(**NULLABLE, verbose_name="владел по")
    owner = models.ForeignKey(Owner, verbose_name="владелец", on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return f'{self.boat} - {self.start_year} - {self.stop_year}'

    class Meta:
        verbose_name = "история"
        verbose_name_plural = "истории"

Chapter_6/Lessons21/order/models.py
from django.db import models


class Order(models.Model):
    boat = models.ForeignKey('boat.Boat', on_delete=models.CASCADE, verbose_name='лодка')
    name = models.CharField(max_length=150, verbose_name='имя')
    email = models.EmailField(max_length=254, verbose_name='почта')
    message = models.TextField(verbose_name='сообщение', blank=True)
    closed = models.BooleanField(default=False, verbose_name='заказ закрыт')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата')

    def __str__(self):
        return f'{self.boat} от {self.email}'

    class Meta:
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

Chapter_6/Lessons21/boat/views.py
from django.shortcuts import render

from boat.models import Boat
from django.views.generic import ListView, DetailView


class BoatListView(ListView):
    model = Boat


class BoatDetailView(DetailView):
    model = Boat

Chapter_6/Lessons21/order/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.generic import CreateView

from boat.models import Boat
from order.models import Order

from order.services import send_order_email


class OrderCreateView(CreateView):
    model = Order
    fields = ('boat', 'name', 'email', 'message', )

    def get_success_url(self):
        return reverse('boat:boat_view', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['boats'] = get_object_or_404(Boat, pk=self.kwargs.get('pk'))
        return context_data

    def form_valid(self, form):
        obj = form.save()
        send_order_email(obj)
        return super().form_valid(form)

Chapter_6/Lessons21/boat/templates/boat/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <title>{% if title %}{{title}} - {% endif %}Продажа лодок</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/pricing.css' %}" rel="stylesheet">
  </head>

  <body>

    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
      <h5 class="my-0 mr-md-auto font-weight-normal">Продажа лодок</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="{% url 'boat:boat_list'%}">Лодки</a>
      </nav>
      {# <a class="btn btn-outline-primary" href="#">Sign up</a> #}
    </div>

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="display-4">{{title}}</h1>
    </div>

    <div class="container">
      <div class="card-deck mb-3 text-center">
          {% block content %}
          {% endblock %}
      </div>

      <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
          <div class="col-12 col-md">
            <img class="mb-2" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
            <small class="d-block mb-3 text-muted">&copy; 2017-2018</small>
          </div>
          <div class="col-6 col-md">
            <h5>Features</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Cool stuff</a></li>
              <li><a class="text-muted" href="#">Random feature</a></li>
              <li><a class="text-muted" href="#">Team feature</a></li>
              <li><a class="text-muted" href="#">Stuff for developers</a></li>
              <li><a class="text-muted" href="#">Another one</a></li>
              <li><a class="text-muted" href="#">Last time</a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Resource</a></li>
              <li><a class="text-muted" href="#">Resource name</a></li>
              <li><a class="text-muted" href="#">Another resource</a></li>
              <li><a class="text-muted" href="#">Final resource</a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>About</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Team</a></li>
              <li><a class="text-muted" href="#">Locations</a></li>
              <li><a class="text-muted" href="#">Privacy</a></li>
              <li><a class="text-muted" href="#">Terms</a></li>
            </ul>
          </div>
        </div>
      </footer>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
    <script>
      Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
      });
    </script>
  </body>
</html>

Chapter_6/Lessons21/boat/templates/boat/boat_detail.html
{% extends 'boat/base.html' %}

{% block content %}
    <div class="card">
        <div class="card-header">{{object.name}}</div>
        <div class="card-body">
        <table class="table table-striped">
            <tr>
                <th>Начало</th>
                <th>Окончание</th>
                <th>Владелец</th>
            </tr>    {% for history_item in object.boathistory_set.all %}
            <tr>
            <td>{{history_item.start_year}}</td>
            <td>
                {% if history_item.stop_year %}
                    {{history_item.stop_year}}
                {% else %}
                    по настоящее время
                {% endif %}
            </td>
            <td>
                {% if history_item.owner %}
                    {{history_item.owner}}
                {% else %}
                    не указан
                {% endif %}
            </td>
            </tr>
            {% endfor %}
        </table>
    </div>
        <div class="card-footer">
        <a href="{% url 'order:create' object.pk %}" class="btn btn-outline-success">Оставить заявку</a>
        </div>
    </div>
{% endblock %}

Chapter_6/Lessons21/boat/templates/boat/boat_list.html
{% extends 'boat/base.html' %}

{% block content %}
    {% for object in object_list %}
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{object.name}}</h4>
            </div>
            <div class="card-body">
                {% if object.price %}
                <h2 class="card-title pricing-card-title">{{object.price}} руб.</h2>
                {% else %}

                <h2 class="card-title pricing-card-title">
                    <small class="text-muted">не указана </small>
                </h2>
                {% endif %}
                <a href="{% url 'boat:boat_view' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-primary">
                    Информация
                </a>
            </div>
        </div>
    {% endfor %}

{% endblock %}

Chapter_6/Lessons21/order/templates/order/order_form.html
{% extends 'boat/base.html' %}

{% block content %}
    <div class="card">
        <div class="card-header">Создание заявки на лодку {{boat}}</div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <input type="hidden"  name="boat_id" value="{{ boat.pk }}">
                {{ form.as_p}}
                <button type="submit" class="btn btn-success">Оставить заявку</button>
            </form>
        </div>
    </div>
{% endblock %}