Chapter_6/CW_Chapter6/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path("users/", include("users.urls", namespace="users")),
    path("blogs/", include("blogs.urls", namespace="blogs")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Chapter_6/CW_Chapter6/main/urls.py
from django.urls import path
from main.apps import MainConfig
from main.views import NewsletterListView, NewsletterDetailView, NewsletterCreateView, NewsletterUpdateView, \
    NewsletterDeleteView, IndexView, ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, \
    ClientDetailView,MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView

from main.views import LogListView

app_name = MainConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),

    path('newsletter/', NewsletterListView.as_view(), name='list_newsletter'),
    path('newsletter/<int:pk>/', NewsletterDetailView.as_view(), name='view_newsletter'),
    path('newsletter/create/', NewsletterCreateView.as_view(), name='create_newsletter'),
    path('newsletter/edit/<int:pk>/', NewsletterUpdateView.as_view(), name='update_newsletter'),
    path('newsletter/delete/<int:pk>/', NewsletterDeleteView.as_view(), name='delete_newsletter'),

    path('client/', ClientListView.as_view(), name='list_client'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='view_client'),
    path('client/create/', ClientCreateView.as_view(), name='create_client'),
    path('client/edit/<int:pk>/', ClientUpdateView.as_view(), name='update_client'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),

    path('message/', MessageListView.as_view(), name='list_message'),
    path('message/<int:pk>/', MessageDetailView.as_view(), name='view_message'),
    path('message/create/', MessageCreateView.as_view(), name='create_message'),
    path('message/edit/<int:pk>/', MessageUpdateView.as_view(), name='update_message'),
    path('message/delete/<int:pk>/', MessageDeleteView.as_view(), name='delete_message'),

    path('log_list/', LogListView.as_view(), name='log_list'),
]

Chapter_6/CW_Chapter6/main/models.py
from django.db import models

from users.models import User

NULLABLE = {"null": True, "blank": True}


class Client(models.Model):
    """Модель для хранения информации о клиенте
    Клиенты — это те, кто получает рассылки, а пользователи — те, кто создает эти рассылки."""

    first_name = models.CharField(max_length=100, verbose_name='имя')
    last_name = models.CharField(max_length=100, verbose_name='фамилия', **NULLABLE)
    email = models.EmailField(max_length=100, verbose_name='email', unique=True)
    comment = models.TextField(verbose_name="комментарий", **NULLABLE)
    owner = models.ForeignKey(User, verbose_name='Владелец', on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return f"Клиент - {self.first_name} {self.last_name} - {self.email}"

    class Meta:
        verbose_name = "клиент"
        verbose_name_plural = "клиенты"


class Message(models.Model):
    """Модель для хранения информации о сообщении для рассылки"""

    message_title = models.CharField(max_length=100, verbose_name='тема письма')
    message_body = models.TextField(verbose_name='тело письма')
    owner = models.ForeignKey(User, verbose_name='Владелец', on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return f"Сообщение с темой {self.message_title}"

    class Meta:
        verbose_name = "сообщение"
        verbose_name_plural = "сообщения"


class Newsletter(models.Model):
    """Модель для хранения информации о рассылке(настройки)"""

    NEWSLETTER_STARTED = 'запущена'
    NEWSLETTER_COMPLETED = 'завершена'
    NEWSLETTER_CREATED = 'создана'

    STATUS_CHOICES = [
        (NEWSLETTER_STARTED, 'запущена'),
        (NEWSLETTER_CREATED, 'создана'),
        (NEWSLETTER_COMPLETED, 'завершена'),
    ]

    MONTH_PERIODICITY = 'month'
    DAY_PERIODICITY = 'day'
    WEEK_PERIODICITY = 'week'
    MINUTE_PERIODICITY = 'minute'

    PERIODICITY_CHOICES = [
        (MONTH_PERIODICITY, 'раз в месяц'),
        (DAY_PERIODICITY, 'раз в день'),
        (WEEK_PERIODICITY, 'раз в неделю'),
        (MINUTE_PERIODICITY, 'раз в минуту'),
    ]

    newsletter_name = models.CharField(max_length=150, verbose_name="Название рассылки")
    start_time = models.DateTimeField(verbose_name='время начала рассылки', **NULLABLE)
    end_time = models.DateTimeField(verbose_name='время окончания рассылки', **NULLABLE)
    periodicity = models.CharField(max_length=100, verbose_name='периодичность', choices=PERIODICITY_CHOICES,
                                   default=MONTH_PERIODICITY)
    status = models.CharField(max_length=100, verbose_name='статус рассылки',
                              default=NEWSLETTER_CREATED, choices=STATUS_CHOICES)

    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='сообщение для клиентов', **NULLABLE)
    client = models.ManyToManyField(Client, verbose_name='Имена клиентов')
    owner = models.ForeignKey(User, verbose_name='Владелец', on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return f"Рассылка: '{self.newsletter_name}'"

    class Meta:
        verbose_name = "рассылка"
        verbose_name_plural = "рассылки"
        ordering = ("newsletter_name",)
        permissions = [
            ('deactivate_mailing', 'Can deactivate mailing'),
            ('view_all_mailings', 'Can view all mailings'),
        ]


class Log(models.Model):
    """Модель для хранения информации о попытках рассылок (логах)"""

    LOG_SUCCESS = 'Успешно'
    LOG_FAIL = 'Неуспешно'

    STATUS_VARIANTS = [
        (LOG_SUCCESS, 'Успешно'),
        (LOG_FAIL, 'Неуспешно'),
    ]

    time = models.DateTimeField(
        verbose_name="Дата и время попытки отправки", auto_now_add=True)
    status = models.CharField(max_length=50, verbose_name='Cтатус рассылки', choices=STATUS_VARIANTS)
    server_response = models.CharField(
        max_length=150, verbose_name="Ответ сервера почтового сервиса", **NULLABLE
    )
    newsletter = models.ForeignKey(Newsletter, verbose_name='рассылка для логов', on_delete=models.CASCADE, **NULLABLE)

    def __str__(self):
        return (f"Рассылка {self.newsletter} от {self.time} со статусом: {self.status}. Ответ сервера почтового "
                f"сервиса:{self.server_response}")

    class Meta:
        verbose_name = "Попытка рассылки"
        verbose_name_plural = "Попытки рассылки"

Chapter_6/CW_Chapter6/main/forms.py
from django import forms
#
from main.models import Newsletter, Client, Message


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if not isinstance(field.widget, forms.CheckboxInput):
                field.widget.attrs['class'] = 'form-control'


class NewsletterForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Newsletter
        fields = '__all__'


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        fields = '__all__'


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        fields = '__all__'


class ManagerNewsletterForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Newsletter
        fields = ('status',)

Chapter_6/CW_Chapter6/main/views.py
from random import random

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied

from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from main.models import Newsletter, Client, Message, Log

from main.forms import NewsletterForm, MessageForm, ClientForm

from main.forms import ManagerNewsletterForm
from main.services import get_newsletter_from_cache


from blogs.services import get_articles_from_cache


class IndexView(TemplateView):
    template_name = 'main/index.html'
    extra_context = {
        'title': 'Главная',
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['mail_count'] = len(get_newsletter_from_cache())
        context_data['active_mail_count'] = len(Newsletter.objects.filter(status__in=('создана', 'запущена')))
        context_data['client_count'] = len(Client.objects.all())
        context_data['random_blogs'] = get_articles_from_cache().order_by('?')[:3]
        return context_data


class NewsletterListView(LoginRequiredMixin, ListView):
    model = Newsletter
    extra_context = {
        'title': "Рассылки ",
    }
    template_name = 'main/newsletter_list.html'
    success_url = reverse_lazy('main:newsletter_list')

    def get_queryset(self, queryset=None):
        queryset = super().get_queryset()
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name='manager'):
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class NewsletterDetailView(LoginRequiredMixin, DetailView):
    model = Newsletter
    extra_context = {
        'title': "Рассылки ",
    }
    success_url = reverse_lazy('main:list_newsletter')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name='manager') and user != self.object.owner:
            raise PermissionDenied
        else:
            return self.object


class NewsletterCreateView(LoginRequiredMixin, CreateView):
    model = Newsletter
    form_class = NewsletterForm
    extra_context = {
        'title': "Рассылки ",
    }
    success_url = reverse_lazy('main:list_newsletter')

    def form_valid(self, form):
        newsletter = form.save()
        user = self.request.user
        newsletter.owner = user
        newsletter.save()
        return super().form_valid(form)


class NewsletterUpdateView(LoginRequiredMixin, UpdateView):
    model = Newsletter
    extra_context = {
        'title': "Рассылки ",
    }
    form_class = NewsletterForm
    success_url = reverse_lazy('main:list_newsletter')

    def get_form_class(self):
        """
        Функция, определяющая поля для редактирования в зависимости от прав пользователя
        """
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            return NewsletterForm
        elif user.has_perm('main.deactivate_mailing'):
            return ManagerNewsletterForm
        else:
            raise PermissionDenied


class NewsletterDeleteView(LoginRequiredMixin, DeleteView):
    model = Newsletter
    extra_context = {
        'title': "Рассылки ",
    }
    success_url = reverse_lazy('main:list_newsletter')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    extra_context = {
        'title': "Клиенты",
    }
    template_name = 'main/client_list.html'
    success_url = reverse_lazy('main:list_client')

    def get_queryset(self, queryset=None):
        queryset = super().get_queryset()
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name='manager'):
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    extra_context = {
        'title': "Клиенты",
    }
    form_class = ClientForm
    success_url = reverse_lazy('main:list_client')

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.owner = user
        client.save()
        return super().form_valid(form)


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client
    extra_context = {
        'title': "Клиенты",
    }
    success_url = reverse_lazy('main:list_client')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    extra_context = {
        'title': "Клиенты",
    }
    form_class = ClientForm
    success_url = reverse_lazy('main:list_client')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    extra_context = {
        'title': "Клиенты",
    }
    success_url = reverse_lazy('main:list_client')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    extra_context = {
        'title': "Сообщения",
    }
    template_name = 'main/message_list.html'
    success_url = reverse_lazy('main:list_message')

    def get_queryset(self, queryset=None):
        queryset = super().get_queryset()
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name='manager'):
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    extra_context = {
        'title': "Сообщения",
    }
    form_class = MessageForm
    success_url = reverse_lazy('main:list_message')

    def form_valid(self, form):
        message = form.save()
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message
    extra_context = {
        'title': "Сообщения",
    }
    success_url = reverse_lazy('main:list_message')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    extra_context = {
        'title': "Сообщения",
    }
    form_class = MessageForm
    success_url = reverse_lazy('main:list_message')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    extra_context = {
        'title': "Сообщения",
    }
    success_url = reverse_lazy('main:list_message')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            return self.object
        raise PermissionDenied


class LogListView(LoginRequiredMixin, ListView):
    """
    Контроллер отвечающий за отображение списка попыток рассылок
    """
    model = Log

Chapter_6/CW_Chapter6/main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <title>{{title}}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>


<header data-bs-theme="dark">
    <div class="collapse text-bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">

                <div class="col-sm-6 offset-md-9 py-4">
                    <ul class="list-unstyled">
                        {% include 'main/includes/inc_main_menu.html' %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a href="{% url 'main:index' %}" class="navbar-brand d-flex align-items-center">
                <strong>Сервис рассылок</strong>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">{{title}}</h1>


        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row">
                {% block content %}
                {% endblock %}

            </div>
        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p>&copy; 2023 - {% now 'Y' %} </p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>


<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
        integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

Chapter_6/CW_Chapter6/main/templates/main/client_confirm_delete.html
{% extends 'main/index.html' %}

{% block content %}
    <div class="col-12">
        <div class=" row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить клиента {{ object|title }}</p>
                            <button type="submit" class="btn btn-danger">Подтвердить
                            </button>
                            <a href="{% url 'main:list_client' %}" class="btn btn-warning">Отменить</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Chapter_6/CW_Chapter6/main/templates/main/client_detail.html
{% extends 'main/index.html'%}
{% block content %}

<div class="col-6">
    <div class="card">
        <div class="card-body">
            <p class="card-text">имя: {{ object.first_name }}</p>
            <p class="card-text">фамилия: {{ object.last_name }}</p>
            <p class="card-text">email: {{ object.email }}</p>
            <p class="card-text">комментарий: {{ object.comment }}</p>

            <div class="btn-group">
                <a class="btn btn-primary" href="{% url 'main:list_client'%}"
                   role="button">Назад</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Chapter_6/CW_Chapter6/main/templates/main/client_form.html
{% extends 'main/index.html'%}
{% block content %}

<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-body">

                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Создать</button>

                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

Chapter_6/CW_Chapter6/main/templates/main/client_list.html
{% extends 'main/index.html' %}
{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'main:create_client' %}">Добавить клиента</a>
</div>

    {% for object in object_list %}
    <div class="col-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <p class="card-text">
                    {{object|title}}
                </p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        {% if user == object.owner or user.is_superuser %}
                        <a class="btn btn-outline-primary" href="{% url 'main:view_client' object.pk %}"
                           role="button">Просмотр</a>

                        <a class="btn btn-outline-primary" href="{% url 'main:update_client' object.pk %}"
                           role="button">Редактировать</a>

                        <a class="btn btn-outline-primary" href="{% url 'main:delete_client' object.pk %}"
                           role="button">Удалить</a>
                        {% endif %}
                    </div>
                    <div class="card-body">
                    Владелец клиента: {{object.owner}}
                </div>
                </div>
            </div>
        </div>
    </div>


{% endfor %}
{% endblock %}

Chapter_6/CW_Chapter6/main/templates/main/index.html
{% extends 'main/base.html' %}
{% load my_tags %}
{% block content %}

<div class="jumbotron">
    <h2>Статистика сервиса рассылок</h2>
    <p class="lead">Количество рассылок всего:  {{mail_count}}</p>
    <p class="lead">Количество активных рассылок: {{active_mail_count}}</p>
    <p class="lead">Количество уникальных клиентов для рассылок: {{client_count}}</p>

<!--        <p><a class="btn btn-lg btn-success" href="#" role="button">Get started today</a></p>-->
</div>


<div class="row">
    {% for object in object_list %}
    {% include 'mails/includes/inc_blog.html' with object=object %}
    {% endfor %}
</div>
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for object in random_blogs %}
            <div class="col-4">
                <div class="card shadow-sm">
                    <img src="{{ object.image | media_filter }}">
                    <div class="card-body">
                        <p class="card-text">
                        <h2>{{ object.title}}</h2>
                        <p class="card-text">Содержание: {{ object.body }}</p>
                        <p class="card-text"> Создана {{ object.created_at }}</p>
                        <p class="card-text">Просмотры- {{ object.views_count }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

Chapter_6/CW_Chapter6/main/templates/main/log_list.html
{% extends 'main/base.html'%}
{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Попытки рассылок</h1>
    </div>
</section>
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">Рассылка</th>
        <th scope="col">Время</th>
        <th scope="col">Статус</th>
        <th scope="col">Ответ сервера</th>
    </tr>
    </thead>
    <tbody>
    {% for log in object_list %}
    <tr>
        <td>{{ log.mailing }}</td>
        <td>{{ log.time }}</td>
        <td>{{ log.status }}</td>
        <td>{{ log.newsletter }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

Chapter_6/CW_Chapter6/main/templates/main/message_confirm_delete.html
{% extends 'main/index.html' %}

{% block content %}
    <div class="col-12">
        <div class=" row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить сообщение {{ object|title }}</p>
                            <button type="submit" class="btn btn-danger">Подтвердить
                            </button>
                            <a href="{% url 'main:list_message' %}" class="btn btn-warning">Отменить</a>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Chapter_6/CW_Chapter6/main/templates/main/message_detail.html
{% extends 'main/index.html'%}
{% block content %}

<div class="col-6">
    <div class="card">
        <div class="card-body">
            <p class="card-text">тема письма: {{ object.message_title }}</p>
            <p class="card-text">тело письма: {{ object.message_body }}</p>

            <div class="btn-group">
                <a class="btn btn-primary" href="{% url 'main:list_message'%}"
                   role="button">Назад</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Chapter_6/CW_Chapter6/main/templates/main/message_list.html
{% extends 'main/index.html' %}
{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'main:create_message' %}">Добавить сообщение</a>
</div>

{% for object in object_list %}
<div class="col-12">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">
                {{object|title}}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    {% if user == object.owner or user.is_superuser or perms.message.view_message%}
                    <a class="btn btn-outline-primary" href="{% url 'main:view_message' object.pk %}"
                       role="button">Просмотр</a>
                    {% endif %}
                    {% if perms.message.change_message or user == object.owner %}

                    <a class="btn btn-outline-primary" href="{% url 'main:update_message' object.pk %}"
                       role="button">Редактировать</a>
                    {% endif %}
                    {% if perms.message.delete_message or user == object.owner%}

                    <a class="btn btn-outline-primary" href="{% url 'main:delete_message' object.pk %}"
                       role="button">Удалить</a>
                    {% endif %}
                </div>
                <div class="card-body">
                    Автор сообщения: {{object.owner}}
                </div>
            </div>

        </div>


    </div>
</div>


{% endfor %}
{% endblock %}

Chapter_6/CW_Chapter6/main/templates/main/newsletter_confirm_delete.html
{% extends 'main/index.html' %}

{% block content %}
    <div class="col-12">
        <div class=" row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить рассылку {{ object|title }}</p>
                            <button type="submit" class="btn btn-danger">Подтвердить
                            </button>
                            <a href="{% url 'main:list_newsletter' %}" class="btn btn-warning">Отменить</a>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Chapter_6/CW_Chapter6/main/templates/main/newsletter_list.html
{% extends 'main/index.html' %}
{% block content %}
<div class="col-12 mb-5">
    {% if user.is_authenticated %}
    <a class="btn btn-outline-primary" href="{% url 'main:create_newsletter' %}">Добавить рассылку</a>
    {% endif %}
</div>

    {% for object in object_list %}
    <div class="col-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <p class="card-text">
                    {{object|title}}
                </p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        {% if perms.main.view_all_mailings or user == object.owner or user.is_superuser %}
                        <a class="btn btn-outline-primary" href="{% url 'main:view_newsletter' object.pk %}"
                           role="button">Просмотр</a>
                        {% endif %}
                        {% if perms.main.deactivate_mailing or user == object.owner or user.is_superuser %}

                        <a class="btn btn-outline-primary" href="{% url 'main:update_newsletter' object.pk %}"
                           role="button">Редактировать</a>
                        {% endif %}
                        {% if user == object.owner or user.is_superuser %}

                        <a class="btn btn-outline-primary" href="{% url 'main:delete_newsletter' object.pk %}"
                           role="button">Удалить</a>
                        {% endif %}
                    </div>
                    <div class="card-body">
                    Автор рассылки: {{object.owner}}
                </div>
                </div>

            </div>
        </div>
    </div>


{% endfor %}
{% endblock %}