Chapter_6/CW_Chapter6/blogs/urls.py
from django.urls import path

from blogs.apps import BlogsConfig
from blogs.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView


app_name = BlogsConfig.name

urlpatterns = [

    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),

]

Chapter_6/CW_Chapter6/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path("users/", include("users.urls", namespace="users")),
    path("blogs/", include("blogs.urls", namespace="blogs")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Chapter_6/CW_Chapter6/main/urls.py
from django.urls import path
from main.apps import MainConfig
from main.views import NewsletterListView, NewsletterDetailView, NewsletterCreateView, NewsletterUpdateView, \
    NewsletterDeleteView, IndexView, ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, \
    ClientDetailView,MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView

from main.views import LogListView

app_name = MainConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),

    path('newsletter/', NewsletterListView.as_view(), name='list_newsletter'),
    path('newsletter/<int:pk>/', NewsletterDetailView.as_view(), name='view_newsletter'),
    path('newsletter/create/', NewsletterCreateView.as_view(), name='create_newsletter'),
    path('newsletter/edit/<int:pk>/', NewsletterUpdateView.as_view(), name='update_newsletter'),
    path('newsletter/delete/<int:pk>/', NewsletterDeleteView.as_view(), name='delete_newsletter'),

    path('client/', ClientListView.as_view(), name='list_client'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='view_client'),
    path('client/create/', ClientCreateView.as_view(), name='create_client'),
    path('client/edit/<int:pk>/', ClientUpdateView.as_view(), name='update_client'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),

    path('message/', MessageListView.as_view(), name='list_message'),
    path('message/<int:pk>/', MessageDetailView.as_view(), name='view_message'),
    path('message/create/', MessageCreateView.as_view(), name='create_message'),
    path('message/edit/<int:pk>/', MessageUpdateView.as_view(), name='update_message'),
    path('message/delete/<int:pk>/', MessageDeleteView.as_view(), name='delete_message'),

    path('log_list/', LogListView.as_view(), name='log_list'),
]

Chapter_6/CW_Chapter6/blogs/models.py
from django.db import models

NULLABLE = {"null": True, "blank": True}


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name="заголовок")
    # slug = models.CharField(max_length=150, verbose_name="slug", **NULLABLE)
    body = models.TextField(verbose_name="содержимое")
    image = models.ImageField(
        upload_to="product/", verbose_name="изображение", **NULLABLE
    )
    published = models.DateTimeField(auto_now_add=True, verbose_name="дата публикации")
    # is_published = models.BooleanField(default=True, verbose_name="опубликовано")
    views_count = models.IntegerField(default=0, verbose_name="просмотры")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "блог"
        verbose_name_plural = "блоги"

Chapter_6/CW_Chapter6/blogs/views.py
from django.template.defaultfilters import slugify
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blogs.models import Blog

from blogs.services import get_articles_from_cache


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'body', 'image')
    success_url = reverse_lazy('blogs:list')


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = get_articles_from_cache()
        return queryset



class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'body')
    success_url = reverse_lazy('blogs:list')

    def get_success_url(self):
        return reverse('blogs:view', kwargs={'pk': self.object.pk})


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blogs:list')

Chapter_6/CW_Chapter6/blogs/templates/blogs/blog_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class=" row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить статью {{ object|title }}</p>
                            <button type="submit" class="btn btn-danger">Подтвердить
                            </button>
                            <a href="{% url 'blogs:list' %}" class="btn btn-warning">Отменить</a>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Chapter_6/CW_Chapter6/blogs/templates/blogs/blog_detail.html
{% extends 'main/base.html'%}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                         <h3 class="card-title">
                             Статья {{ object.title }}  ({{ object.slug }})
                         </h3>
                    </div>
                    <div class="card-body">
                        <img src="/media/{{object.image}}" style="object-fit: cover; width: 100%; height: 50%"/>
                        <p>
                            {{ object.body }}
                        </p>
                    </div>
                    <div class="card-footer">
                        Просмотры {{ object.views_count}}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Chapter_6/CW_Chapter6/blogs/templates/blogs/blog_form.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class=" row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <p>
                            {{ object.body }}
                        </p>
                    </div>
                    <div class="card-body">

                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Chapter_6/CW_Chapter6/blogs/templates/blogs/blog_list.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="col-12 mb-5">
        <a class="btn btn-outline-primary" href="{% url 'blogs:create' %}">Добавить статью</a>
    </div>
    {% for object in object_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <img src="/media/{{object.image}}" style="object-fit: cover; width: 100%; height: 50%"/>
                    <p class="card-text">
                        {{object|title}}

                    </p>
                    <div class="d-flex justify-content-between align-items-center mb-4">
                        <div class="btn-group">
                            <a href="{% url 'blogs:view' object.pk %}"
                                       class="btn btn-sm btn-outline-secondary">Просмотр</a>
                            <a href="{% url 'blogs:edit' object.pk %}"
                                       class="btn btn-sm btn-outline-secondary">Рeдактировать</a>
                            <a href="{% url 'blogs:delete' object.pk %}"
                                       class="btn btn-sm btn-outline-danger">Удалить</a>

                        </div>
                    </div>
                    <div class="card-footer">
                        Просмотры {{ object.views_count}}
                    </div>
                    <div class="card-footer">
                        Дата публикации -  {{ object.published}}
                    </div>
                </div>
            </div>
        </div>
{% endfor %}
{% endblock %}